# language: php

# tests: true

filter:
    excluded_paths:
        - 'Tests/*'

tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true
    sensiolabs_security_checker: true

checks:
    php: true

build:
    tests:
        override:
            -
                command: phpunit --configuration phpunit-scrutinizer.xml --coverage-clover=logs/clover.xml
                coverage:
                    file: logs/clover.xml
                    format: clover
