filter:
    excluded_paths:
        - 'Tests/sniff-examples/*'

tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true
    sensiolabs_security_checker: true

checks:
    php: true

build:
    tests:
        override:
            -
                command: phpunit --configuration phpunit-travis.xml --coverage-clover build/logs/clover.xml
                coverage:
                    file: build/logs/clover.xml
                    format: php-clover