# language: php

# tests: true

filter:
    excluded_paths:
        - 'Tests/sniff-examples/*'

tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true
    sensiolabs_security_checker: true

checks:
    php: true
