sudo: false

dist: trusty

cache:
  apt: true

language: php

## Cache composer downloads.
cache:
  directories:
    # Cache directory for older Composer versions.
    - $HOME/.composer/cache/files
    # Cache directory for more recent Composer versions.
    - $HOME/.cache/composer/files

env:
  global:
    - COVERALLS_VERSION="notset"
    - PHPUNIT_VERSION="travis"
  matrix:
    # `master`, i.e PHPCS 3.x.
    - PHPCS_VERSION="dev-master" LINT=1

matrix:
  fast_finish: true
  include:
    # N.B.: Coverage is only checked on the lowest and highest stable PHP versions for all PHPCS versions.

    - php: 7.2
      env: PHPCS_VERSION="dev-master" LINT=1 SNIFF=1 COVERALLS_VERSION="^2.0"
      addons:
        apt:
          packages:
            - libxml2-utils

  allow_failures:
    # Allow failures for unstable builds.
    - php: nightly
    - php: hhvm

before_install:
  # Speed up build time by disabling Xdebug when its not needed.
  - if [[ $COVERALLS_VERSION == "notset" && $TRAVIS_PHP_VERSION != "nightly" && $TRAVIS_PHP_VERSION != "hhvm" ]]; then phpenv config-rm xdebug.ini; fi
  - export XMLLINT_INDENT="    "
  # PHP 5.3+: set up test environment using Composer.
  - composer self-update
  - if [[ $COVERALLS_VERSION != "notset" ]]; then composer require php-coveralls/php-coveralls:${COVERALLS_VERSION}; fi
  - composer require squizlabs/php_codesniffer:${PHPCS_VERSION}
  - if [[ $PHPUNIT_VERSION != "travis" ]]; then composer require phpunit/phpunit:${PHPUNIT_VERSION}; fi
  # --no-dev makes sure the Travis provided version of PHPUnit is used for better stability.
  # --prefer-dist will allow for optimal use of the travis caching ability.
  - composer install --no-dev --prefer-dist

before_script:
  - if [[ $COVERALLS_VERSION != "notset" ]]; then mkdir -p build/logs; fi
  - phpenv rehash
  - if [[ $COVERALLS_VERSION != "notset" && $TRAVIS_PHP_VERSION == "7.2" ]]; then echo "<?php xdebug_set_filter(XDEBUG_FILTER_CODE_COVERAGE, XDEBUG_PATH_WHITELIST, [ '$(pwd)/PHPCompatibility/Sniffs/' ]);" > .xdebug_filter.php; fi

script:
  # Lint all PHP files against parse errors.
  # Run the unit tests.
  - if [[ $PHPUNIT_VERSION == "travis" && $COVERALLS_VERSION != "notset" && $TRAVIS_PHP_VERSION == "7.2" ]]; then phpunit -dauto_preprend_file=$(pwd)/.xdebug_filter.php --configuration phpunit-travis.xml --coverage-clover build/logs/clover.xml; fi
  - if [[ $PHPUNIT_VERSION == "travis" && $COVERALLS_VERSION != "notset" && $TRAVIS_PHP_VERSION != "7.2" ]]; then phpunit --configuration phpunit-travis.xml --coverage-clover build/logs/clover.xml; fi
  - if [[ $PHPUNIT_VERSION != "travis" && $COVERALLS_VERSION != "notset" ]]; then vendor/bin/phpunit --configuration phpunit-travis.xml --coverage-clover build/logs/clover.xml; fi
  - if [[ $PHPUNIT_VERSION == "travis" && $COVERALLS_VERSION == "notset" ]]; then phpunit; fi
  - if [[ $PHPUNIT_VERSION != "travis" && $COVERALLS_VERSION == "notset" ]]; then vendor/bin/phpunit; fi

after_success:
  - if [[ $COVERALLS_VERSION == "^1.0" ]]; then php vendor/bin/coveralls -v -x build/logs/clover.xml; fi
  - if [[ $COVERALLS_VERSION == "^2.0" ]]; then php vendor/bin/php-coveralls -v -x build/logs/clover.xml; fi
