#!/usr/bin/env php
<?php

$autoloadPath = dirname(dirname($argv[0])). '/autoload.php';

if (!file_exists($autoloadPath)) {
    $autoloadPath = dirname(dirname(dirname(dirname($argv[0])))) . '/autoload.php';
}

require($autoloadPath);

// Remove the standard from the PHPCS installed-standards.
PHPCompatibility_Scripts_Register::disable();
